Added necessary dependencies for Si7021 temp sensor
SiliconLabs/sdk_support pull request #76
Opened 2022-10-10 20:48 UTC by CuRahman

#### Problem / Feature
Generated and added necessary files for the Si7021 Temperature Sensor

#### Change overview
Added necessary includes as well as generated files

#### Testing
Flashed image using the sensor onto a 4161A

2022-10-11 12:49 UTC, mkardous-silabs requested changes
Is it normal that only the files for the BRD4161A were generated and not all the supported boards?

2022-10-11 12:49 UTC, mkardous-silabs commented on matter/efr32/efr32mg12/BRD4161A/autogen/sl_event_handler.c
> +#include "sl_i2cspm_instances.h"
This should be only included if the sensor is needed and not by default.

2022-10-11 12:49 UTC, mkardous-silabs commented on matter/efr32/efr32mg12/BRD4161A/autogen/sl_event_handler.c
> +    sl_i2cspm_init_instances();
Same comment as include

2022-10-13 14:28 UTC, jepenven-silabs approved these changes

2022-10-13 14:53 UTC, mkardous-silabs approved these changes

2022-10-13 14:55 UTC, merged